### ISSUE TITLE
Connector stops to pull data from FIFO after several minutes

### ISSUE THREAD

**Issue by DafuSHI** [DatavenueLiveObjects/Flexible_Engine_DIS_LOconnector_to_install_on_FE#3]
Hello,

After the Connector is up and running,it will consume all the messages in FIFO. But after several miutes the connector will stay up however stops pulling messages from FIFO.

Could you please check the root cause for it?

Regards
Dafu

**Comment by szlisiecki** [comment]
Hello Dafu,

I've updated connector. Indeed there was a bug. Default "keepAlive" parameter was set to 0. Now it's changed to 60 seconds in sdk library. Please pull the latest version from main branch.

Best regards
Szymon Lisiecki

**Comment by grzegorzswistak** [comment]
I'm closing this issue because it has been fixed.
